[build]
  command = "npm run build && make"
  publish = "dist"
  functions = "functions"
[build.environment]
  GO_IMPORT_PATH = "github.com/Colelyman/colelyman-hugo"

[context.deploy-preview]
  command = "npm run build-preview"
