baseurl = "https://colelyman.com"
languageCode = "en-us"
languageLang = "en"
title = "cole lyman"
author = "Cole Lyman"

theme = "indieweb-lanyon-hugo"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
pygmentsuseclasses = true
pygmentsstyle = "emacs"

[permalinks]
post = ":year/:month/:day/:title/"
fixed = ":title/"

[params]
Title = "cole lyman"
Tagline = "Bioinformatics, Emacs, Programming, and Life"
Author = "Cole Lyman"
DateForm = "Jan 2 2006"

  [params.Github]
  Url = "http://github.com/Colelyman/indieweb-lanyon-hugo"
  Head = "master"

  [params.Handles]
  Twitter = "colelyman"
  Github = "Colelyman"
  Email = "cole@colelyman.com"

  [params.Webmention]
  Domain = "http://colelyman.com/"
  Endpoint = "https://webmention.io/"
  Account = "colelyman.com"

